### The PyTorch API
Ref: https://lightning.ai/courses/deep-learning-fundamentals/3-0-overview-model-training-in-pytorch/3-5-the-pytorch-api-parts-1-2/

In [2]:
import torch

In [ ]:
# class MyModel(torch.nn.Module):
#     def __init__(self):
#         super(MyModel, self).__init__()
#         # define parameters

#     def forward(self, x):
#         # return outputs

In [4]:
linear = torch.nn.Linear(in_features=2, out_features=1)
print(f'weights: {linear.weight}') # auto init weights
print(f'bias: {linear.bias}') # auto init bias

weights: Parameter containing:
tensor([[-0.0696,  0.0149]], requires_grad=True)
bias: Parameter containing:
tensor([-0.6319], requires_grad=True)


In [6]:
x = torch.tensor([1.0, 2.0]) # single training example
z = linear(x)
z

tensor([-0.6716], grad_fn=<AddBackward0>)

In [8]:
x = torch.tensor([[1.0, 2.0], 
                  [3.0, 4.0],
                  [4.0, 5.0]]) # 3 training examples
z = linear(x)
z

tensor([[-0.6716],
        [-0.7808],
        [-0.8355]], grad_fn=<AddmmBackward0>)